config/routes.rb
Ticketee::Application.routes.draw do
  root :to => "projects#index"
  resources :projects do
    resources :tickets
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, :dependent => :delete_all
  validates_presence_of :name
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  
  validates_presence_of :title
  validates_presence_of :description
  validates_length_of :title, :minimum => 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, :except => [:new, :index, :create]
  def index
    @projects = Project.find(:all)
  end
  
  def show

  end
  
  def new
    @project = Project.new
  end
  
  def edit

  end
  
  def create
    @project = Project.new(params[:project])
    @project.save
    if @project.save
      flash[:notice] = "Project has been created"
      redirect_to(@project)
    else
      flash[:alert] = "Project has not been created"
      render :action => 'new'
    end
  end
  
  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated"
      redirect_to(@project)
    else
      flash[:alert] = "Project has not been updated"
      render :action => "edit"
    end
  end
  
  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end
  
  private
  def find_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" +
    " for could not be found."
    redirect_to projects_path
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_project
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
  def new
    @ticket = @project.tickets.build
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated"
      redirect_to([@project,@ticket])
    else
      flash[:alert] = "Ticket has not been updated"
      render :action => "edit"
    end
  end
  
  def create
    @ticket = @project.tickets.build(params[:ticket])
    if @ticket.save
      flash[:notice] = "Ticket has been created"
      redirect_to([@project,@ticket])
    else
      flash[:alert] = "Ticket has not been created"
      render :action => "new"
    end
  end
  
  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted"
    redirect_to(@project)
  end
  
  private 
  
  def find_project
    @project = Project.find(params[:project_id])
  end
  
  def find_ticket
    @ticket = @project.tickets.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title(*params)
    unless params.empty?
      content_for :title do
        (params << "Ticketee").join(" - ") unless params.empty?
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if content_for?(:title) %>
	   <%= yield(:title)%>
	<% else %>
	  Ticketee
	<% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value %>
	</div>
<% end %>
<h1><%= link_to "Ticketee", root_path %></h1>
<%= yield %>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| -%>
  <% @project.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
  <% end %>
  <p>
  	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>
  </p>

  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end -%>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render "form" %>

app/views/projects/index.html.erb
<h3>Welcome</h3>

<%= link_to "New Project", new_project_path %>

<% @projects.each do |project| %>
	<li><%= link_to project.name, project %> | <%= link_to "edit", edit_project_path(project) %></li>
<% end %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %> | <%= link_to "Edit", edit_project_path(@project) %> | <%= link_to "Delete Project", @project, :method => :delete,
:confirm => "Are you sure you want to delete this project?" %></h2>

<%= link_to "New Ticket", new_project_ticket_path(@project) %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
    #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %> | 	<%= link_to "Delete Ticket", [@project, ticket], :method => :delete,
		:confirm => "Are you sure you want to delete this ticket?" %>
    </li>
  <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project,@ticket] do |f| -%>
  <% @ticket.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
  <% end %>
  <p>
  	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>
  </p>
  <p>
  	<%= f.label :description, "Description" %>
	<%= f.text_area :description %>
  </p>
  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end -%>

app/views/tickets/edit.html.erb
<h2>Edit Ticket</h2>

<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>

<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <%= simple_format(@ticket.description) %> | <%= link_to "Edit", edit_project_ticket_path(@project,@ticket) %> | <%= link_to "Delete Ticket", [@project, @ticket], :method => :delete,
:confirm => "Are you sure you want to delete this ticket?" %>
</div>